/**
 * ParkEase - Dataset for Indian Tier-1 Cities Parking Spots
 * Real-world locations with coordinates, rates, amenities, and real-time statuses
 */

const CITIES_DATA = {
    delhi: {
        name: "Delhi NCR",
        center: [28.6139, 77.2090],
        zoom: 13,
        spots: [
            {
                id: "del-01",
                name: "CP Block B Underground Multi-Level Parking",
                city: "delhi",
                area: "Connaught Place, Central Delhi",
                lat: 28.6328,
                lng: 77.2197,
                type: "Multilevel Underground",
                operator: "NDMC Smart Parking",
                verified: true,
                rating: 4.6,
                totalReviews: 840,
                rates: { twoWheeler: 20, fourWheeler: 40, suv: 50, dayPass: 250 },
                slots: { total: 450, available: 42, evSlots: 6, evAvailable: 2 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "24/7 Guard", "Elevator", "Restrooms"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 11 2334 5678"
            },
            {
                id: "del-02",
                name: "Cyber Hub Basement P2 Smart Park",
                city: "delhi",
                area: "DLF Cyber City, Gurugram",
                lat: 28.4952,
                lng: 77.0886,
                type: "Corporate Basement",
                operator: "DLF Facilities",
                verified: true,
                rating: 4.8,
                totalReviews: 1240,
                rates: { twoWheeler: 30, fourWheeler: 60, suv: 80, dayPass: 400 },
                slots: { total: 600, available: 115, evSlots: 15, evAvailable: 5 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Valet Available", "24/7 Guard"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 124 456 7890"
            },
            {
                id: "del-03",
                name: "Select Citywalk Open & Basement Parking",
                city: "delhi",
                area: "Saket District Centre, South Delhi",
                lat: 28.5283,
                lng: 77.2195,
                type: "Mall Parking",
                operator: "Citywalk Logistics",
                verified: true,
                rating: 4.5,
                totalReviews: 920,
                rates: { twoWheeler: 25, fourWheeler: 50, suv: 70, dayPass: 300 },
                slots: { total: 800, available: 8, evSlots: 8, evAvailable: 1 },
                amenities: ["CCTV", "Covered", "Fastag", "Valet Available", "Restrooms"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "10:00 AM - 12:00 AM",
                contactPhone: "+91 11 4211 4200"
            },
            {
                id: "del-04",
                name: "Hauz Khas Village Municipal Parking",
                city: "delhi",
                area: "HKV Entrance, South Delhi",
                lat: 28.5535,
                lng: 77.1945,
                type: "Surface Open Lot",
                operator: "MCD Delhi",
                verified: true,
                rating: 3.9,
                totalReviews: 430,
                rates: { twoWheeler: 15, fourWheeler: 35, suv: 45, dayPass: 180 },
                slots: { total: 120, available: 3, evSlots: 0, evAvailable: 0 },
                amenities: ["CCTV", "Guard on Duty", "Cash & UPI Accepted"],
                fastagEnabled: false,
                image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "08:00 AM - 11:30 PM",
                contactPhone: "+91 11 2652 1199"
            },
            {
                id: "del-05",
                name: "Noida Sector 18 Multilevel Car Park (Atta)",
                city: "delhi",
                area: "Sector 18 Commercial Hub, Noida",
                lat: 28.5708,
                lng: 77.3261,
                type: "Multilevel Automated",
                operator: "Noida Authority",
                verified: true,
                rating: 4.3,
                totalReviews: 760,
                rates: { twoWheeler: 20, fourWheeler: 40, suv: 50, dayPass: 220 },
                slots: { total: 950, available: 210, evSlots: 10, evAvailable: 4 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Elevator", "Restrooms"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 120 252 5050"
            }
        ]
    },

    mumbai: {
        name: "Mumbai",
        center: [19.0760, 72.8777],
        zoom: 13,
        spots: [
            {
                id: "mum-01",
                name: "BKC One Underground Smart Lot",
                city: "mumbai",
                area: "Bandra Kurla Complex, Bandra East",
                lat: 19.0664,
                lng: 72.8687,
                type: "Multilevel Underground",
                operator: "MMRDA Parking System",
                verified: true,
                rating: 4.7,
                totalReviews: 950,
                rates: { twoWheeler: 30, fourWheeler: 80, suv: 100, dayPass: 500 },
                slots: { total: 550, available: 68, evSlots: 12, evAvailable: 4 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Valet Available", "Elevator"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 22 2659 0001"
            },
            {
                id: "mum-02",
                name: "Linking Road BMC Pay & Park",
                city: "mumbai",
                area: "Linking Road, Bandra West",
                lat: 19.0607,
                lng: 72.8339,
                type: "Surface Street Authorized",
                operator: "BMC Authorized",
                verified: true,
                rating: 4.1,
                totalReviews: 620,
                rates: { twoWheeler: 25, fourWheeler: 60, suv: 80, dayPass: 350 },
                slots: { total: 110, available: 4, evSlots: 0, evAvailable: 0 },
                amenities: ["CCTV", "Guard on Duty", "UPI Accepted"],
                fastagEnabled: false,
                image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "09:00 AM - 11:00 PM",
                contactPhone: "+91 22 2642 3344"
            },
            {
                id: "mum-03",
                name: "Nariman Point CR2 Multilevel Parking",
                city: "mumbai",
                area: "CR2 Mall, Nariman Point, South Mumbai",
                lat: 18.9272,
                lng: 72.8228,
                type: "Multilevel Automated",
                operator: "Inorbit / BMC",
                verified: true,
                rating: 4.6,
                totalReviews: 830,
                rates: { twoWheeler: 30, fourWheeler: 70, suv: 90, dayPass: 450 },
                slots: { total: 400, available: 45, evSlots: 8, evAvailable: 3 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Restrooms"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "07:00 AM - 12:00 AM",
                contactPhone: "+91 22 6655 4433"
            },
            {
                id: "mum-04",
                name: "Phoenix Palladium Car Deck",
                city: "mumbai",
                area: "Lower Parel, Central Mumbai",
                lat: 18.9953,
                lng: 72.8242,
                type: "Mall Multi-Deck",
                operator: "Phoenix Mills Management",
                verified: true,
                rating: 4.8,
                totalReviews: 1450,
                rates: { twoWheeler: 40, fourWheeler: 90, suv: 120, dayPass: 600 },
                slots: { total: 1100, available: 180, evSlots: 20, evAvailable: 8 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Valet Available", "Car Wash"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 22 4333 9999"
            }
        ]
    },

    bengaluru: {
        name: "Bengaluru",
        center: [12.9716, 77.5946],
        zoom: 13,
        spots: [
            {
                id: "blr-01",
                name: "Indiranagar 100ft Road Smart Hub",
                city: "bengaluru",
                area: "Near 12th Main Junction, Indiranagar",
                lat: 12.9719,
                lng: 77.6412,
                type: "Multilevel Automated",
                operator: "BBMP Smart City",
                verified: true,
                rating: 4.5,
                totalReviews: 680,
                rates: { twoWheeler: 20, fourWheeler: 50, suv: 60, dayPass: 280 },
                slots: { total: 320, available: 24, evSlots: 6, evAvailable: 2 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Elevator"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "07:00 AM - 11:30 PM",
                contactPhone: "+91 80 2520 1234"
            },
            {
                id: "blr-02",
                name: "Koramangala 5th Block SafeSpot",
                city: "bengaluru",
                area: "Industrial Layout, Koramangala 5th Block",
                lat: 12.9352,
                lng: 77.6245,
                type: "Dedicated Surface Lot",
                operator: "ParkEase Private Host",
                verified: true,
                rating: 4.7,
                totalReviews: 510,
                rates: { twoWheeler: 15, fourWheeler: 40, suv: 50, dayPass: 240 },
                slots: { total: 85, available: 12, evSlots: 3, evAvailable: 1 },
                amenities: ["CCTV", "Guard on Duty", "Fastag", "UPI Accepted"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 98450 11223"
            },
            {
                id: "blr-03",
                name: "Church Street / MG Road Metro Parking",
                city: "bengaluru",
                area: "Brigade Road Crossing, Central Bengaluru",
                lat: 12.9748,
                lng: 77.6078,
                type: "Underground Metro Lot",
                operator: "BMRCL Smart Mobility",
                verified: true,
                rating: 4.6,
                totalReviews: 1120,
                rates: { twoWheeler: 15, fourWheeler: 45, suv: 55, dayPass: 250 },
                slots: { total: 420, available: 6, evSlots: 8, evAvailable: 0 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Metro Card / Fastag", "Elevator"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "05:00 AM - 11:30 PM",
                contactPhone: "+91 80 2296 8555"
            },
            {
                id: "blr-04",
                name: "Whitefield ITPL TechPark Visitor Parking",
                city: "bengaluru",
                area: "Pattandur Agrahara, Whitefield",
                lat: 12.9866,
                lng: 77.7281,
                type: "Multilevel Covered",
                operator: "Ascendas ITPL",
                verified: true,
                rating: 4.8,
                totalReviews: 890,
                rates: { twoWheeler: 20, fourWheeler: 40, suv: 50, dayPass: 220 },
                slots: { total: 850, available: 160, evSlots: 20, evAvailable: 7 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Restrooms", "Food Court Access"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 80 4188 0000"
            }
        ]
    },

    pune: {
        name: "Pune",
        center: [18.5204, 73.8567],
        zoom: 13,
        spots: [
            {
                id: "pun-01",
                name: "FC Road Deccan Smart Parking",
                city: "pune",
                area: "Fergusson College Road, Shivajinagar",
                lat: 18.5246,
                lng: 73.8415,
                type: "Multilevel Mechanical",
                operator: "PMC Smart City",
                verified: true,
                rating: 4.4,
                totalReviews: 540,
                rates: { twoWheeler: 15, fourWheeler: 40, suv: 50, dayPass: 200 },
                slots: { total: 280, available: 18, evSlots: 4, evAvailable: 1 },
                amenities: ["CCTV", "Covered", "Fastag", "Elevator", "Security"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "08:00 AM - 11:30 PM",
                contactPhone: "+91 20 2550 1000"
            },
            {
                id: "pun-02",
                name: "Hinjewadi Phase 1 Quadron Parking Hub",
                city: "pune",
                area: "Rajiv Gandhi Infotech Park, Hinjewadi",
                lat: 18.5912,
                lng: 73.7389,
                type: "Covered Corporate Deck",
                operator: "MIDC / Hinjewadi Industries",
                verified: true,
                rating: 4.7,
                totalReviews: 780,
                rates: { twoWheeler: 15, fourWheeler: 35, suv: 45, dayPass: 180 },
                slots: { total: 600, available: 95, evSlots: 10, evAvailable: 5 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "24/7 Guard"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 20 6676 0000"
            },
            {
                id: "pun-03",
                name: "Koregaon Park North Main Road Spot",
                city: "pune",
                area: "Lane 6, Koregaon Park",
                lat: 18.5362,
                lng: 73.8938,
                type: "Private Host Lot",
                operator: "ParkEase Verified Host",
                verified: true,
                rating: 4.6,
                totalReviews: 320,
                rates: { twoWheeler: 20, fourWheeler: 50, suv: 60, dayPass: 250 },
                slots: { total: 45, available: 5, evSlots: 2, evAvailable: 0 },
                amenities: ["CCTV", "Gated Security", "UPI QR Code"],
                fastagEnabled: false,
                image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "08:00 AM - 01:00 AM",
                contactPhone: "+91 97654 32100"
            }
        ]
    },

    hyderabad: {
        name: "Hyderabad",
        center: [17.3850, 78.4867],
        zoom: 13,
        spots: [
            {
                id: "hyd-01",
                name: "Hitec City Cyber Towers Smart Bay",
                city: "hyderabad",
                area: "Madhapur, Hitec City",
                lat: 17.4504,
                lng: 78.3808,
                type: "Multilevel Covered",
                operator: "TSIIC / L&T Infocity",
                verified: true,
                rating: 4.7,
                totalReviews: 1040,
                rates: { twoWheeler: 20, fourWheeler: 45, suv: 60, dayPass: 230 },
                slots: { total: 700, available: 82, evSlots: 14, evAvailable: 4 },
                amenities: ["CCTV", "Covered", "EV Fast Charging", "Fastag", "Restrooms", "24/7 Guard"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "24 Hours (Mon - Sun)",
                contactPhone: "+91 40 6636 1234"
            },
            {
                id: "hyd-02",
                name: "Banjara Hills Road No. 1 GVK Lot",
                city: "hyderabad",
                area: "Road No. 1, Banjara Hills",
                lat: 17.4208,
                lng: 78.4487,
                type: "Mall Basement",
                operator: "GHMC Authorized",
                verified: true,
                rating: 4.5,
                totalReviews: 670,
                rates: { twoWheeler: 25, fourWheeler: 50, suv: 70, dayPass: 280 },
                slots: { total: 350, available: 14, evSlots: 4, evAvailable: 1 },
                amenities: ["CCTV", "Covered", "Fastag", "Valet Available"],
                fastagEnabled: true,
                image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=600&auto=format&fit=crop&q=80",
                towingFreeGuaranteed: true,
                operatingHours: "09:00 AM - 11:30 PM",
                contactPhone: "+91 40 4476 7777"
            }
        ]
    }
};

// Additional mock live data updater for realistic simulation
const SIMULATED_COMMUNITY_STATS = {
    totalSpotsAcrossCities: "18,400+",
    activeBookingsToday: "4,920",
    averageSearchTimeSaved: "18 mins",
    towingCasesPrevented: "3,150+"
};
